version: '3.9'

services:
  app:
    image: 'sun-service-docker'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
     - SPRING_DATASOURCE_URL=postgres://strawberry_user:2IDcC41CycPVbgd7FqPy6wfZGdOI09Mf@dpg-cp5hfuv79t8c73eucjlg-a/strawberry
     - SPRING_DATASOURCE_USERNAME=strawberry_user
     - SPRING_DATASOURCE_PASSWORD=2IDcC41CycPVbgd7FqPy6wfZGdOI09Mf
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=strawberry_user
      - POSTGRES_PASSWORD=2IDcC41CycPVbgd7FqPy6wfZGdOI09Mf