name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # указать вашу основную ветку

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run tests
        run: |
          ./gradlew test  # или используйте ваш собственный скрипт для запуска тестов

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # необходимо для доступа к репозиторию GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # токен доступа к SonarCloud
